// Generated by scripts/build-emoji.ts: the emoji with a 3D icon in public/emoji.
export const EMOJI: ReadonlySet<string> = new Set([
  "1f319",
  "1f34e",
  "1f3af",
  "1f44b-1f3fd",
  "1f4a1",
  "1f4dd",
  "1f50d",
  "1f534",
  "1f600",
  "1f606",
  "1f9ed",
  "2139-fe0f",
  "2600-fe0f",
  "26a0-fe0f",
  "2705",
  "274c",
  "a9-fe0f"
])
