// Vendors Fluent Emoji 3D (MIT, via @lobehub/fluent-emoji-3d) for every emoji used in content/.
// Run after adding a new emoji: npm run emoji. Files are committed; builds never download.
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs"

import { emojiCode, findEmoji } from "../lib/emoji.ts"

const CDN = "https://unpkg.com/@lobehub/fluent-emoji-3d@1.1.0/assets/"
const content = new URL("../content/", import.meta.url)
const out = new URL("../public/emoji/", import.meta.url)
mkdirSync(out, { recursive: true })

const used = new Set<string>()
for (const f of readdirSync(content, { recursive: true }) as string[])
  if (f.endsWith(".md"))
    for (const e of findEmoji(readFileSync(new URL(f, content), "utf8"))) used.add(e)

// The package names some files with U+FE0F and some without: try both.
const candidates = (code: string) => [
  code,
  code.replace(/-fe0f/g, ""),
  code.includes("-") ? code : `${code}-fe0f`,
]

const missing: string[] = []
for (const e of used) {
  const code = emojiCode(e)
  const file = new URL(`${code}.webp`, out)
  if (existsSync(file)) continue
  let ok = false
  for (const c of new Set(candidates(code))) {
    const res = await fetch(CDN + c + ".webp")
    if (!res.ok) continue
    writeFileSync(file, Buffer.from(await res.arrayBuffer()))
    console.log(`+ ${e} ${code}`)
    ok = true
    break
  }
  if (!ok) missing.push(`${e} (${code})`)
}

const codes = readdirSync(out).filter((f) => f.endsWith(".webp")).map((f) => f.slice(0, -5)).sort()
writeFileSync(
  new URL("../lib/emoji-manifest.ts", import.meta.url),
  `// Generated by scripts/build-emoji.ts: the emoji with a 3D icon in public/emoji.\n` +
    `export const EMOJI: ReadonlySet<string> = new Set(${JSON.stringify(codes, null, 2)})\n`
)
console.log(`${codes.length} icons in public/emoji`)
if (missing.length) console.log(`No 3D icon for: ${missing.join(", ")} (shown as plain emoji)`)
